version: "2"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - err113
    - exhaustive
    - exhaustruct
    - lll
    - mnd
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - varnamelen

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^spew\.Print(f|ln)?$
        - pattern: ^spew\.Dump$
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - paramTypeCombine # already handle by gofumpt.extra-rules
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        hugeParam:
          sizeThreshold: 220
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
    gosec:
      excludes:
        - G204
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    mnd:
      ignored-functions:
        - os.*
    tagalign:
      align: false
      order:
        - json
        - csv
    tagliatelle:
      case:
        rules:
          csv: goCamel
          json: goCamel

  exclusions:
    presets:
      - comments
    rules:
      - path: (.+)_test.go
        linters:
          - dupl
          - funlen
          - goconst
          - maintidx

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
