package main

import (
	"slices"
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_sortResult(t *testing.T) {
	results := []*Result{
		{
			ForkURL:       "https://github.com/aaydin-tr/flock",
			Owner:         "aaydin-tr",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...aaydin-tr:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/cluetrust/flock",
			Owner:         "cluetrust",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...cluetrust:flock:master",
			Behind:        22,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/mikhail-artemev/flock",
			Owner:         "mikhail-artemev",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...mikhail-artemev:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/JackMordaunt/flock",
			Owner:         "JackMordaunt",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...JackMordaunt:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/onflowser/flock",
			Owner:         "onflowser",
			Repo:          "flock",
			Ahead:         3,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...onflowser:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/moskyb/flock",
			Owner:         "moskyb",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...moskyb:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/juicedata/flock",
			Owner:         "juicedata",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...juicedata:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/88250/flock",
			Owner:         "88250",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...88250:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/trying2016/flock",
			Owner:         "trying2016",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...trying2016:flock:master",
			Behind:        57,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/pgavlin/flock",
			Owner:         "pgavlin",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...pgavlin:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/ujjwalsh/flock",
			Owner:         "ujjwalsh",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...ujjwalsh:flock:master",
			Behind:        57,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/fearful-symmetry/flock",
			Owner:         "fearful-symmetry",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...fearful-symmetry:flock:master",
			Behind:        68,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/kakami/flock",
			Owner:         "kakami",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...kakami:flock:master",
			Behind:        57,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/wataash/flock",
			Owner:         "wataash",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...wataash:flock:master",
			Behind:        68,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/virtuald/go-flock",
			Owner:         "virtuald",
			Repo:          "go-flock",
			Ahead:         4,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...virtuald:go-flock:master",
			Behind:        93,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
	}

	slices.SortFunc(results, sortResult)

	expected := []*Result{
		{
			ForkURL:       "https://github.com/cluetrust/flock",
			Owner:         "cluetrust",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...cluetrust:flock:master",
			Behind:        22,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/onflowser/flock",
			Owner:         "onflowser",
			Repo:          "flock",
			Ahead:         3,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...onflowser:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/moskyb/flock",
			Owner:         "moskyb",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...moskyb:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/88250/flock",
			Owner:         "88250",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...88250:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/aaydin-tr/flock",
			Owner:         "aaydin-tr",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...aaydin-tr:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/juicedata/flock",
			Owner:         "juicedata",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...juicedata:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/JackMordaunt/flock",
			Owner:         "JackMordaunt",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...JackMordaunt:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/mikhail-artemev/flock",
			Owner:         "mikhail-artemev",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...mikhail-artemev:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/pgavlin/flock",
			Owner:         "pgavlin",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...pgavlin:flock:master",
			Behind:        55,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/trying2016/flock",
			Owner:         "trying2016",
			Repo:          "flock",
			Ahead:         2,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...trying2016:flock:master",
			Behind:        57,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/ujjwalsh/flock",
			Owner:         "ujjwalsh",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...ujjwalsh:flock:master",
			Behind:        57,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/kakami/flock",
			Owner:         "kakami",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...kakami:flock:master",
			Behind:        57,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/fearful-symmetry/flock",
			Owner:         "fearful-symmetry",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...fearful-symmetry:flock:master",
			Behind:        68,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/wataash/flock",
			Owner:         "wataash",
			Repo:          "flock",
			Ahead:         1,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...wataash:flock:master",
			Behind:        68,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
		{
			ForkURL:       "https://github.com/virtuald/go-flock",
			Owner:         "virtuald",
			Repo:          "go-flock",
			Ahead:         4,
			AheadURL:      "https://github.com/gofrs/flock/compare/main...virtuald:go-flock:master",
			Behind:        93,
			Stars:         0,
			Forks:         0,
			Issues:        0,
			DefaultBranch: "master",
		},
	}

	assert.Equal(t, expected, results)
}
